functions_path: ../../../manuscripts/mgefish/code/functions
# input_table: input_table_test.csv
# input_table: input_table_nonproblem.csv
# input_table: input_table_20240506.csv
# input_table: input_table_problemchild.csv
# input_table: input_table_problem1.csv
# input_table: input_table_problem2.csv
input_table: input_table_all.csv
output_dir: ../outputs/segmentation_2024_03_07
max_shift: 500
gauss: 3
diff_gauss: (2, 3)
bg_smoothing: 5
n_clust_bg: 10
top_n_clust_bg: 9
im_inches: 2.3622
im_ft: 7
clips: (0,0.75)
rgb_clips: [[0,0.1],[0,0.1],[0,0.1]]
dpi: 850
cb_col: 'w'
n_clust: 25
spec_dims: (10,5)
umap_dims: (5,5)
s_u: 1
alpha_u: 0.25
cmap_u: 'Spectral'
ref_dir: "../../../manuscripts/mgefish/data/unused/fig_5/HiPRFISH_reference_spectra"

plot_spectra:
  xs: [3, 7, 10, 24, 27, 29, 31, 33, 43, 47,57, 60]


dict_clip:
  2023_02_18_hsdm_group_IV_patient_1_fov_01: (0.0.25)

color_legend:
  label_color: 'k'
  ft: 8
  dims: (1.5,2.5)

moran:
  radius_um: 3
  lw: 1
  ft: 7
  dims: (2, 1)
  l_col: 'k'
  pad: 0.2
  dpi: 500
  spot_size: 1
  dims_im: (4,4)
l_func:
  lw: 2
  dims: (2,1)
  ft: 7
  dmax: 205
  stepsize: 5
cluster_size:
  lw: 1
  ft: 7
  dims_cl: (4,4)
  spot_size: 1
  dpi: 250
  dims_pl: (2,1)
  min_cluster_size: 10

min_box_size_um: 10

fuzzy_box_counting:
  box_edge_init_um: 50
  divide_edgesize: 1.5
  box_edge_min_um: 5
  col: 'k'
  ft: 7
  dims: (4,4)
  slope_xloc: 30

multifractal_analysis:
  box_edge_init_um: 150
  divide_edgesize: 1.5
  box_edge_min_um: 5
  col: 'k'
  ft: 7
  dims: (4,4)
  slope_xloc: 1000
  qmin: -4
  qmax: 6
  cmap: 'tab10'

power_spectrum:
  step_um: 5
  radius_um: 10
  fmin: 0.01
  fmax: 0.1
